### ISSUE TITLE
How to use this tool with webdriverIO

### ISSUE THREAD

**Issue by amiya-pattnaik** [tamil777selvan/wdio-axe#1]

**Comment by tamil777selvan** [comment]
Hi Amiya,

A sample implementation of wdio-axe can be found in [OSEAN](https://github.com/tamil777selvan/OSEAN)

[Feature File Path](https://github.com/tamil777selvan/OSEAN/blob/master/tests/wdio/features/e2e/accessibilityCheck.feature)
[Step Definition Path](https://github.com/tamil777selvan/OSEAN/blob/master/tests/wdio/features/step_definitions/axe.step.js)

For time being I have consoled the axe [output](https://travis-ci.com/tamil777selvan/OSEAN/jobs/246911028) , it can also attach to cucumber report.

Thanks,
Tamil

**Comment by amiya-pattnaik** [comment]
Hi Tamil,
Thanks for the information. I liked the approach.Few things I want to know. can it takes the screenshot and highlight the fields where it finds the web accessibility rules are broken ? I found a tool called as AATT from paypal which does the same things but it is tightly coupled with there tools. Below is the link for your reference.
paypal/AATT

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
paypal/AATT

Automated Accessibility Testing Tool. Contribute to paypal/AATT development by creating an account on GitHub.
 |

 |

 |


Please advise.
Thanks in advance.Amiya

    On Thursday, 17 October, 2019, 06:05:56 pm GMT-5, Tamil Selvan <notifications@github.com> wrote:  
 
 
Hi Amiya,

A sample implementation of wdio-axe can be found in OSEAN

Feature File Path
Step Definition Path

For sample I have consoled the axe output , it can also attach to cucumber report.

Thanks,
Tamil

**Comment by tamil777selvan** [comment]
Thanks for the feedback Amiya. Yes, it is possible to take screenshots of particular element for which the WCAG accessibility guidelines is not followed.

**Comment by amiya-pattnaik** [comment]
Thanks Tamil,
I actually tried with my webdriver.io code. I am not getting screen shots etc related to WCAG.
Can you please add some sample code which takes a screen shots and high light the html element where WCAG rules fail.

Thanks in advance.

**Comment by tamil777selvan** [comment]
Hi Amiya,

I have used a [small logic](https://travis-ci.org/tamil777selvan/OSEAN/builds/610830506) which saves the screenshot of element for which accessibility is failed. But was unsuccessful in highlighting it in same page. 

Thanks in advance!!
